[package]
name = "delv-sea-shell"
version = "0.1.0"
authors = ["Delvoid"]
edition = "2021"


[dependencies]
anyhow = "1.0.68"    # error handling
bytes = "1.3.0"      # helps manage buffers
dirs = "5.0.1"
thiserror = "1.0.38" # error handling
